CREATE TABLE businessowner (
   ownerID INT AUTO_INCREMENT PRIMARY KEY,
   fname VARCHAR(255),
   lname VARCHAR(255),
   date_registered DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ecommercewebsites (
   websiteID INT AUTO_INCREMENT PRIMARY KEY,
   ownerID INT,
   businessName VARCHAR(255),
   domain VARCHAR(255),
   websiteStatus VARCHAR(255),
   date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
   username VARCHAR(255),
   last_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
   user_id INT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(255),
   password VARCHAR(255),
   date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);